export const appColors = {
    primary: '#5669FF',
    white: '#FFFFFF',
    text: '#120D26',
    gray: '#807A7A',
    gray2: '#DADADA',
    gray3: '#EBEBEB',
    link: '#5669FF',
    danger: '#e74c3c',
    disabledText: '#FFFFFF',
    disabled: '#BDBDBD',
    success : '#00FF11',
    btncity: '#CFF6B7',
    btnDay: '#b9e0f7',
    inputDay: '#f1f2d0',
    btnaddActivity: '#FF9D9F',
};